### ISSUE TITLE
Markdown display fields should word-wrap

### ISSUE THREAD

**Issue by gmr** [AWeber-Imbi/imbi-ui#25]
When text is too long to show in the given field, it should wrap.

![Screenshot 2022-11-02 at 12 42 19 PM](https://user-images.githubusercontent.com/49469/199550940-0111ea02-2cbe-4e28-b08d-bba3df35896a.png)

**Comment by dave-shawley** [comment]
Likely related to https://github.com/AWeber-Imbi/imbi-ui/blob/eed422d06eb2f55fcc281cb6956def6a2573d592/src/js/views/OperationsLog/Display.jsx#L58
